services:
  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - jk-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - jk-network

volumes:
  mongo-data:

networks:
  jk-network:
    driver: bridge
